### ISSUE TITLE
GeoJSON support

### ISSUE THREAD

**Issue by junosuarez** [max-mapper/nextbus-live-feed#2]
I wrote a [similar program](https://github.com/jden/carta-streaming-api/) for bus data in Chattanooga, TN. I was also converting from xml to json, and chose to model my json output as GeoJSON for compatibility with other tools - https://github.com/jden/carta-streaming-api/issues/9 . Would you consider support for GeoJSON and/or accept pull requests? If this repo isn't the right place, what would be?

Cheers!

**Comment by max-mapper** [comment]
yea i'd be happy storing a geojson column instead of a lat/lon column, but the algorithm itself is pretty tied to the nextbus API, would you be able to use this at all for bustracker.gocarta.org?

**Comment by junosuarez** [comment]
Ideally it'd be nice to have bus APIs converge on GeoJSON Features / FeatureCollections with `property` fields derived from GTFS column names. The xml parsing side of it would have to differ depending on the underlying vendor, but the output format could be relatively similar.

I understand that DAT is largely columnar, and GeoJSON is mostly tree-based, but in the simple case, the tree structure is easy enough that it could be flattened predictably:

``` json
{
  "type": "Feature",
  "geometry": { "coordinates": [x, y] },
  "id": 1,
   "properties": { "whatever": "else" }
}
```

could become

```
type | geometry_coordinates_x | geometry_coordinates_y | id | whatever
```
- Is there currently an algorithm for representing flattened trees / denormalized relational structures in dat?

**Comment by max-mapper** [comment]
@jden I prefer to just `JSON.stringify()` any nested data into a cell to keep things simple (dat does this by default when you save nested JSON). I've tried flattening data and it ends up being more trouble than it's worth IMO
